/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nesvadba.tomas.celldetection.gui;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import org.jdesktop.swingx.JXTreeTable;
import org.jdesktop.swingx.treetable.FileSystemModel;
import org.jdesktop.swingx.treetable.TreeTableModel;

/**
 *
 * @author nipaba
 */
public class FilePanel extends javax.swing.JPanel {

    private int index = 0;
    private int maxIndex = 0;

    JXTreeTable jXTreeTable;

    /**
     * Creates new form filePanel
     */
    public FilePanel() {
        initComponents();

        TreeTableModel treeTableModel = new FileSystemModel(); // any TreeTableModel
        JXTreeTable treeTable = new JXTreeTable(treeTableModel);
        JScrollPane scrollpane = new JScrollPane(treeTable);
        
        add(scrollpane,BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btnPreviousFile = new javax.swing.JButton();
        btnNextFile = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jButton2.setText("jButton2");

        setLayout(new java.awt.BorderLayout(0, 10));

        btnPreviousFile.setText("Previous");
        btnPreviousFile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPreviousFile.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPreviousFile.setMaximumSize(new java.awt.Dimension(75, 75));
        btnPreviousFile.setPreferredSize(new java.awt.Dimension(75, 75));
        btnPreviousFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousFileActionPerformed(evt);
            }
        });
        add(btnPreviousFile, java.awt.BorderLayout.LINE_START);

        btnNextFile.setText("Next");
        btnNextFile.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnNextFile.setMaximumSize(new java.awt.Dimension(75, 75));
        btnNextFile.setPreferredSize(new java.awt.Dimension(75, 75));
        btnNextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextFileActionPerformed(evt);
            }
        });
        add(btnNextFile, java.awt.BorderLayout.CENTER);
        add(jProgressBar1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousFileActionPerformed
        if (index != 0) {
            index--;
        }
    }//GEN-LAST:event_btnPreviousFileActionPerformed

    private void btnNextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextFileActionPerformed
        if (index < maxIndex) {
            index++;
        }
    }//GEN-LAST:event_btnNextFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextFile;
    private javax.swing.JButton btnPreviousFile;
    private javax.swing.JButton jButton2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    public int getIndex() {
        return index;
    }

    public void setMaxIndex(int max) {
        maxIndex = max;
    }

}
