/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nesvadba.tomas.celldetection.gui;

import java.util.List;

import javax.swing.JFrame;

import org.apache.log4j.Logger;
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.core.Point;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.imgproc.Imgproc;

import com.nesvadba.tomas.celldetection.domain.ImageFile;
import com.nesvadba.tomas.celldetection.enums.ImageType;
import com.nesvadba.tomas.celldetection.util.CCTops;

/**
 *
 * @author nipaba
 */
public class MainWindow extends javax.swing.JFrame {

    private MainWindowOperationsImpl mwOps;
    private List<ImageFile> files;

    private Mat initMat;
    private static final Logger LOGGER = Logger.getLogger(MainWindow.class);

    /**
     * // * Creates new form MainWindow
     */
    public MainWindow() {
	initComponents();

	setExtendedState(JFrame.MAXIMIZED_BOTH);
	setVisible(true);

	mwOps = new MainWindowOperationsImpl();
	files = mwOps.loadFolder(this);
	mwOps.getInitImage(files.get(0));
	ImageFile file = files.get(0);
	// mwOps.proccessBasic(file);
	// canvas.setIcon(new
	// ImageIcon(ImgConverter.Mat2BufferedImage(file.getData().get(ImageType.SEGMENTED))));
	Mat init = file.getData().get(ImageType.INITIAL);
	Mat gray = new Mat(init.size(), CvType.CV_8UC3);
	Imgproc.cvtColor(init, gray, Imgproc.COLOR_RGB2GRAY);

	Mat denoise = new Mat();
	Imgproc.GaussianBlur(gray, denoise, new Size(new Point(15.0, 15.0)), 5);

	Mat dst = new Mat();
	Mat ones = Mat.ones(init.size(), CvType.CV_8U);
	ones.setTo(new Scalar(255.0), ones);
	Core.absdiff(ones, denoise, dst);
	dst.convertTo(dst, CvType.CV_8U);

	// canvas.setIcon(new ImageIcon(ImgConverter.Mat2BufferedImage(dst)));

	initMat = dst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	canvas = new javax.swing.JLabel();
	controlPanel = new javax.swing.JPanel();
	Basic = new javax.swing.JButton();
	jButton1 = new javax.swing.JButton();
	jButton2 = new javax.swing.JButton();
	filePanel = new FilePanel();
	statsPanel = new StatsPanel();
	jMenuBar1 = new javax.swing.JMenuBar();
	jMenu1 = new javax.swing.JMenu();
	miOpenFile = new javax.swing.JMenuItem();
	miOpenFolder = new javax.swing.JMenuItem();
	miSaveFolder = new javax.swing.JMenuItem();
	miSaveFile = new javax.swing.JMenuItem();
	jSeparator1 = new javax.swing.JPopupMenu.Separator();
	miExit = new javax.swing.JMenuItem();
	jMenu2 = new javax.swing.JMenu();
	miPreferences = new javax.swing.JMenuItem();
	jMenu3 = new javax.swing.JMenu();
	miAbout = new javax.swing.JMenuItem();
	miHelp = new javax.swing.JMenuItem();
	jMenu4 = new javax.swing.JMenu();
	miExportToExcel = new javax.swing.JMenuItem();
	miExportToCSV = new javax.swing.JMenuItem();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	setBackground(new java.awt.Color(0, 0, 0));
	setPreferredSize(new java.awt.Dimension(1500, 800));

	canvas.setBackground(new java.awt.Color(0, 0, 0));
	canvas.setOpaque(true);
	getContentPane().add(canvas, java.awt.BorderLayout.CENTER);

	controlPanel.setBackground(new java.awt.Color(255, 102, 102));

	Basic.setText("Basic");
	Basic.addActionListener(new java.awt.event.ActionListener() {
	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		BasicActionPerformed(evt);
	    }
	});
	controlPanel.add(Basic);

	jButton1.setText("jButton1");
	controlPanel.add(jButton1);

	jButton2.setText("jButton2");
	controlPanel.add(jButton2);

	getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_END);

	filePanel.setBackground(new java.awt.Color(0, 255, 102));
	getContentPane().add(filePanel, java.awt.BorderLayout.LINE_START);

	statsPanel.setBackground(new java.awt.Color(255, 153, 153));
	getContentPane().add(statsPanel, java.awt.BorderLayout.LINE_END);

	jMenu1.setText("File");

	miOpenFile.setText("open File");
	miOpenFile.addActionListener(new java.awt.event.ActionListener() {
	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		miOpenFileActionPerformed(evt);
	    }
	});
	jMenu1.add(miOpenFile);

	miOpenFolder.setText("open Folder");
	miOpenFolder.addActionListener(new java.awt.event.ActionListener() {
	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		miOpenFolderActionPerformed(evt);
	    }
	});
	jMenu1.add(miOpenFolder);

	miSaveFolder.setText("save Folder");
	jMenu1.add(miSaveFolder);

	miSaveFile.setText("save File");
	jMenu1.add(miSaveFile);
	jMenu1.add(jSeparator1);

	miExit.setText("exit");
	jMenu1.add(miExit);

	jMenuBar1.add(jMenu1);

	jMenu2.setText("Edit");

	miPreferences.setText("preferences");
	jMenu2.add(miPreferences);

	jMenuBar1.add(jMenu2);

	jMenu3.setText("About");

	miAbout.setText("about");
	jMenu3.add(miAbout);

	miHelp.setText("help");
	jMenu3.add(miHelp);

	jMenuBar1.add(jMenu3);

	jMenu4.setText("Export");

	miExportToExcel.setText("export to Excel");
	jMenu4.add(miExportToExcel);

	miExportToCSV.setText("export to Csv");
	miExportToCSV.addActionListener(new java.awt.event.ActionListener() {
	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		miExportToCSVActionPerformed(evt);
	    }
	});
	jMenu4.add(miExportToCSV);

	jMenuBar1.add(jMenu4);

	setJMenuBar(jMenuBar1);

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BasicActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BasicActionPerformed
	CCTops a = new CCTops();
	a.temp(initMat);
    }// GEN-LAST:event_BasicActionPerformed

    private void miExportToCSVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miExportToCSVActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_miExportToCSVActionPerformed

    private void miOpenFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miOpenFileActionPerformed

    }// GEN-LAST:event_miOpenFileActionPerformed

    private void miOpenFolderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miOpenFolderActionPerformed
	files = mwOps.loadFolder(this);

    }// GEN-LAST:event_miOpenFolderActionPerformed

    /**
     * @param args
     *            the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // // <editor-fold defaultstate="collapsed" desc=" Look and feel setting
    // // code (optional) ">
    // /*
    // * If Nimbus (introduced in Java SE 6) is not available, stay with the
    // * default look and feel. For details see
    // * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
    // * html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {s
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // }
    // // </editor-fold>
    //
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // @Override
    // public void run() {
    // new MainWindow().setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Basic;
    private javax.swing.JLabel canvas;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel filePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miExportToCSV;
    private javax.swing.JMenuItem miExportToExcel;
    private javax.swing.JMenuItem miHelp;
    private javax.swing.JMenuItem miOpenFile;
    private javax.swing.JMenuItem miOpenFolder;
    private javax.swing.JMenuItem miPreferences;
    private javax.swing.JMenuItem miSaveFile;
    private javax.swing.JMenuItem miSaveFolder;
    private javax.swing.JPanel statsPanel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenu getjMenu1() {
	return jMenu1;
    }

    public void setjMenu1(javax.swing.JMenu jMenu1) {
	this.jMenu1 = jMenu1;
    }

    public javax.swing.JMenu getjMenu2() {
	return jMenu2;
    }

    public void setjMenu2(javax.swing.JMenu jMenu2) {
	this.jMenu2 = jMenu2;
    }

    public javax.swing.JMenuBar getjMenuBar1() {
	return jMenuBar1;
    }

    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
	this.jMenuBar1 = jMenuBar1;
    }

}
