/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nesvadba.tomas.celldetection.gui;

import java.util.HashMap;
import java.util.Map;

import com.nesvadba.tomas.celldetection.enums.FilterProps;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author nipaba
 */
public class StatsPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatsPanel
     */
    private MainWindow mw;
    private Map<FilterProps, Integer> filterProperties = new HashMap<>();

    private SpinnerNumberModel minSpinner = new SpinnerNumberModel();
    private SpinnerNumberModel maxSpinner = new SpinnerNumberModel();

    public StatsPanel() {
        initComponents();
    }

    public StatsPanel(MainWindow mwInput) {
        filterProperties.put(FilterProps.SIZE_MIN, 0);
        filterProperties.put(FilterProps.SIZE_MAX, 500);

        initComponents();
        mw = mwInput;

        minSpinner.setMinimum(0);
        minSpinner.setMaximum(9999999);

        maxSpinner.setMinimum(0);
        maxSpinner.setMaximum(9999999);

        minValueSpinner.setModel(minSpinner);
        maxValueSpinner.setModel(maxSpinner);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filter = new javax.swing.JButton();
        minValueSpinner = new javax.swing.JSpinner();
        maxValueSpinner = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Max Size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Min Size");
        jPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel3.setText("other");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        filter.setText("filter");
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(filter, gridBagConstraints);

        minValueSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minValueSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(minValueSpinner, gridBagConstraints);

        maxValueSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxValueSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(maxValueSpinner, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jSpinner3, gridBagConstraints);

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void minValueSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_minValueSpinnerStateChanged
        int min = (int) minSpinner.getValue();
        filterProperties.put(FilterProps.SIZE_MIN, min);
        mw.refilter(filterProperties);
    }//GEN-LAST:event_minValueSpinnerStateChanged

    private void maxValueSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxValueSpinnerStateChanged
        int max = (int) maxSpinner.getValue();
        filterProperties.put(FilterProps.SIZE_MAX, max);
        mw.refilter(filterProperties);
    }//GEN-LAST:event_maxValueSpinnerStateChanged

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_filterActionPerformed
        mw.refilter(filterProperties);
    }// GEN-LAST:event_filterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner maxValueSpinner;
    private javax.swing.JSpinner minValueSpinner;
    // End of variables declaration//GEN-END:variables
}
